language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
before_install:
  - sudo apt-get install -qq libzmq3-dev libsodium-dev
before_script:
  - ./node_modules/bower/bin/bower install
cache:
  directories:
    - node_modules
    - res/bower_components
