language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
addons:
  apt:
    packages:
    - libzmq3-dev
    - libprotobuf-dev
    - graphicsmagick
before_script:
  - ./node_modules/bower/bin/bower install
cache:
  directories:
    - node_modules
    - res/bower_components
